// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiUJiU66Aziq5XoUZW-1aKgRYgX5e45a4',
    appId: '1:566382409350:android:eba17f6803161428770307',
    messagingSenderId: '566382409350',
    projectId: 'reddit-clone-226be',
    storageBucket: 'reddit-clone-226be.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCG3-7rWweQZnDhCY6ijFkpuB_nd3uqdOw',
    appId: '1:566382409350:ios:84439b29ed98d29f770307',
    messagingSenderId: '566382409350',
    projectId: 'reddit-clone-226be',
    storageBucket: 'reddit-clone-226be.firebasestorage.app',
    iosBundleId: 'com.example.reddit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDkx7rHsINqFcT690nF6hiBsbd5LsNxFbg',
    appId: '1:566382409350:web:5f70a80d3a22ab7b770307',
    messagingSenderId: '566382409350',
    projectId: 'reddit-clone-226be',
    authDomain: 'reddit-clone-226be.firebaseapp.com',
    storageBucket: 'reddit-clone-226be.firebasestorage.app',
  );
}
